version: '2.2'

services:
  database:
    image: "postgres:9.6"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    links:
    - database
    depends_on:
      database:
        condition: service_healthy
    build: .
    environment:
      RACK_ENV:
      RAILS_ENV:
      DATABASE_URL:
      SECRET_KEY_BASE:
      ADMIN_EMAILS:

      # SENDGRID or SES
      SMTP_PROVIDER:

      # Sendgrid
      SENDGRID_USERNAME:
      SENDGRID_PASSWORD:

      # SES
      SES_ADDRESS:
      SES_USERNAME:
      SES_PASSWORD:
      SES_DOMAIN:
      SES_PORT:

      MAILER_FROM_ADDRESS:
